#!/bin/sh

CONTAINER=$1

sudo rmdir \
/sys/fs/cgroup/cpu,cpuacct/$CONTAINER \
/sys/fs/cgroup/cpuset/$CONTAINER \
/sys/fs/cgroup/devices/$CONTAINER \
/sys/fs/cgroup/blkio/$CONTAINER \
/sys/fs/cgroup/memory/$CONTAINER \
/sys/fs/cgroup/net_cls,net_prio/$CONTAINER \
/sys/fs/cgroup/pids/$CONTAINER

for TARGET in `cat containers/$CONTAINER/volumes`
do
  ./umountv $CONTAINER $TARGET
done

sudo umount containers/$CONTAINER/fs/union
rm -rf containers/$CONTAINER
