#!/bin/sh

CONTAINER=$1
USER=$2
CMD=$3
DROP="cap_chown"
ENV="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
PID=`cat /sys/fs/cgroup/memory/800eed18b1538/tasks | head -n1`

if [ -z $CMD ]
then
  CMD="/bin/sh"
fi

sudo nsenter \
  --net=/run/netns/$CONTAINER \
  --pid=/proc/$PID/ns/pid \
  --mount=/proc/$PID/ns/mnt \
  --uts=/proc/$PID/ns/uts \
  --ipc=/proc/$PID/ns/ipc \
  chroot --userspec $USER containers/$CONTAINER/fs/union \
    env $ENV $CMD
