#!/bin/sh

CONTAINER=$1
VOLUME=$2
TARGET=$3

mkdir -p containers/$CONTAINER/fs/union/$TARGET
sudo mount --bind volumes/$VOLUME containers/$CONTAINER/fs/union/$TARGET
echo $TARGET >> containers/$CONTAINER/volumes
