#!/bin/sh

CONTAINER=$1
IMAGE=$2

mkdir -p containers/$CONTAINER/fs/diff
mkdir -p containers/$CONTAINER/fs/work
mkdir -p containers/$CONTAINER/fs/union

sudo mount -t overlay -o \
upperdir=containers/$CONTAINER/fs/diff,\
lowerdir=images/$IMAGE,\
workdir=containers/$CONTAINER/fs/work \
none \
containers/$CONTAINER/fs/union
