#!/bin/sh

CONTAINER=$1
LAYERS=$2

LOWERDIR=`echo $LAYERS | tr ":" " " | xargs printf "images/%s:"`
LOWERDIR="${LOWERDIR%?}"

mkdir -p containers/$CONTAINER/fs/diff
mkdir -p containers/$CONTAINER/fs/work
mkdir -p containers/$CONTAINER/fs/union
mkdir -p containers/$CONTAINER/fs/config/dev
cp initc containers/$CONTAINER/fs/config/.initc
sudo mknod -m 666 containers/$CONTAINER/fs/config/dev/null c 1 3
sudo mknod -m 666 containers/$CONTAINER/fs/config/dev/zero c 1 5
touch containers/$CONTAINER/volumes

sudo mount -t overlay -o \
upperdir=containers/$CONTAINER/fs/diff,\
lowerdir=containers/$CONTAINER/fs/config:$LOWERDIR,\
workdir=containers/$CONTAINER/fs/work \
none \
containers/$CONTAINER/fs/union

sudo mkdir \
/sys/fs/cgroup/cpu,cpuacct/$CONTAINER \
/sys/fs/cgroup/cpuset/$CONTAINER \
/sys/fs/cgroup/devices/$CONTAINER \
/sys/fs/cgroup/blkio/$CONTAINER \
/sys/fs/cgroup/memory/$CONTAINER \
/sys/fs/cgroup/net_cls,net_prio/$CONTAINER \
/sys/fs/cgroup/pids/$CONTAINER
