#!/bin/sh

CONTAINER=$1
USER=$2
CMD=$3
DROP="cap_chown"
ENV="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

if [ -z $CMD ]
then
  CMD="/bin/sh"
fi

sudo mkdir -p /run/netns
sudo touch /run/netns/$CONTAINER

sudo sh -c "echo $$ > /sys/fs/cgroup/cpu,cpuacct/$CONTAINER/tasks"
#sudo sh -c "echo $$ > /sys/fs/cgroup/cpuset/$CONTAINER/tasks"
sudo sh -c "echo $$ > /sys/fs/cgroup/devices/$CONTAINER/tasks"
sudo sh -c "echo $$ > /sys/fs/cgroup/blkio/$CONTAINER/tasks"
sudo sh -c "echo $$ > /sys/fs/cgroup/memory/$CONTAINER/tasks"
sudo sh -c "echo $$ > /sys/fs/cgroup/net_cls,net_prio/$CONTAINER/tasks"
sudo sh -c "echo $$ > /sys/fs/cgroup/pids/$CONTAINER/tasks"

sudo unshare \
  --net=/run/netns/$CONTAINER \
  --pid \
  --mount \
  --uts \
  --ipc \
  --fork \
  chroot --userspec $USER containers/$CONTAINER/fs/union \
    env $ENV /.initc $CMD

sudo umount /run/netns/$CONTAINER
sudo rm /run/netns/$CONTAINER
