#!/bin/sh

CONTAINER=$1
USER=$2
CMD=$3

if [ -z $CMD ]
then
  CMD="/bin/sh"
fi

sudo mkdir -p /run/netns
sudo touch /run/netns/$CONTAINER

sudo unshare --net=/run/netns/$CONTAINER --pid --fork --mount chroot --userspec $USER containers/$CONTAINER/fs/union /.initc $CMD

sudo umount /run/netns/$CONTAINER
sudo rm /run/netns/$CONTAINER
