#!/bin/sh

CONTAINER=`cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 13 | head -n 1`
IMAGE="alpine"
USER="root"
CMD="/bin/sh"

./clean
./pulli $IMAGE
./newc $CONTAINER $IMAGE
./startc $CONTAINER $USER $CMD
./delc $CONTAINER
./clean
